version: '3'
services:
        server:
                build: .
                image: quantumobile/papiea:1545645693
                volumes:
                        - ./:/code
                depends_on:
                        - mongo
                ports:
                        - "3000:3000"
        mongo:
                image: mongo:4.1