version: '3'
services:
        server:
                build: .
                image: nutanix-docker.jfrog.io/papiea:latest
                volumes:
                        - ./:/code
                depends_on:
                        - mongo
                ports:
                        - "3333:3000"
        mongo:
                image: mongo:4.1