version: '3'
services:
        server:
                build: .
                image: quantumobile/papiea:1545645693
                volumes:
                        - ./:/code
                ports:
                        - "3000:3000"
