version: '3'
services:
        server:
                build:
                        dockerfile: .circleci/Dockerfile
                        context: .
                environment:
                        - JEST_JUNIT_OUTPUT=reports/junit/results.xml
                        - AUTHORIZER=CasbinAllowAnonymousAuthorizer
                depends_on:
                        - mongo
        mongo:
                image: mongo:4.1