version: '3'
services:
        server:
                build:
                        dockerfile: .circleci/Dockerfile
                        context: .
                environment:
                        - JEST_JUNIT_OUTPUT=reports/junit/results.xml
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                depends_on:
                        - mongo
        mongo:
                image: mongo:4.1