version: '3'
services:
        server:
                build:
                        dockerfile: .circleci/Dockerfile
                        context: .
                depends_on:
                        - mongo
        mongo:
                image: mongo:4.1