version: '3'
services:
        server:
                build:
                        dockerfile: .circleci/Dockerfile
                        context: .
                ports:
                        - "3000:3000"
